### ISSUE TITLE
after creating docker containers on windows cannot composer req api

### ISSUE THREAD

**Issue by Swicku** [dunglas/symfony-docker#194] opened 2021-12-07 11:15 UTC
I am currently trying to add api-platform to project. Project was made following instructions from [README.md](https://github.com/dunglas/symfony-docker/blob/main/README.md) file but as result im always getting error (result after typing `composer req api` command in php's container cli) : 

![image](https://user-images.githubusercontent.com/44904330/145018324-9ab9e99b-ca3c-46e8-8c74-96f2015959c6.png)

Tried tips from error message but also without any results. 

Is anybody aware what does that mean or how to make it work ?

**Comment by dunglas** [comment] 2021-12-07 12:27
It's because a dependency blocks PHP 8.1. Try adding: `--ignore-platform-req=php`

**Comment by Swicku** [comment] 2021-12-07 18:18
thanks for reply, unfortunately proposed solution did not made difference. For now managed to get it to work by pasting some other composer.json as i want to experiment a bit with caddy server. If pasted composer.json file would be needed i will gladly post it here (not pasting it now as im doubting in such scenario).

**Comment by pietereggink** [comment] 2021-12-15 13:40
The issue is that API Platform does not support PHP 6 currently. see PR https://github.com/api-platform/core/pull/4582

**Comment by maxhelias** [comment] 2021-12-15 18:19
Just a little patience, it should be resolved soon 😄  In the meantime as it is not related to this project, I allow myself to close the issue.

**Closed by maxhelias** 2021-12-15 18:19 UTC
