### ISSUE TITLE
bin/console is missing after install

### ISSUE THREAD

**Issue by 0x346e3730** [dunglas/symfony-docker#163] opened 2021-06-22 19:07 UTC
Title says it all, with latest version of main.

![image](https://user-images.githubusercontent.com/28731165/122984962-e463bd00-d39d-11eb-9913-a035dc437db3.png)

**Comment by 0x346e3730** [comment] 2021-06-22 20:20
Didn't replicated on Linux, happened on Windows. 

I changed `SKELETON: ${SKELETON:-symfony/skeleton}` to `SKELETON: ${SKELETON:-symfony/website-skeleton}` and ran `docker-compose build --pull --no-cache` to install the website skeleton on Windows, something went wrong in the process.

**Comment by maxhelias** [comment] 2021-08-01 19:57
I don't have a Window ready to reproduce the case. Can you check that the configuration of docker for window is correct ? 
It looks like a permission issue to create the file.

**Comment by Nayte91** [comment] 2021-08-18 12:20
Sorry for the naive answer but isn't because there is 
bin/*
!bin/console

on lines 28/29 of .dockerignore ?

**Comment by maxhelias** [comment] 2021-08-18 12:27
The `.dockerignore` file is there to optimize the ADD or COPY command during the build (https://docs.docker.com/engine/reference/builder/#dockerignore-file). The `bin/console` file is retrieved when creating the symfony skeleton in the build process with the symfony recipes.

**Comment by maxhelias** [comment] 2021-08-18 12:30
And the mounted volume here : https://github.com/dunglas/symfony-docker/blob/9d192405e001d802a9cd65dffdb5758345f660fa/docker-compose.override.yml#L8 eecover the creation that was done on the container during the build on the local machine

**Comment by freiondrej-lmc** [comment] 2022-04-07 14:10
is this possibly the same as https://github.com/dunglas/symfony-docker/issues/231?

**Comment by maxhelias** [comment] 2022-09-16 09:57
I'm closing this issue because it is impossible for us to reproduce this problem.
Anyway it seems to be more related to the window file management

**Closed by maxhelias** 2022-09-16 09:57 UTC
Labels: stalled, missing information, cannot reproduce
