### ISSUE TITLE
Clear cache on Dockerfile has issue with FileLoader.php

### ISSUE THREAD

**Issue by h-rafiee** [dunglas/symfony-docker#153] opened 2021-06-13 08:59 UTC
Hello Dear Team,

We had a deployment today on servers, nothing changes but get below error as FileLoader.php cannot found or failed 

``` sh
!!  In FileLoader.php line 173:
!!                                                                                 
!!    The routing file "/srv/app/config/routes/framework.yaml" contains unsupport  
!!    ed keys for "when@dev": "_errors". Expected one of: "resource", "type", "pr  
!!    efix", "path", "host", "schemes", "methods", "defaults", "requirements", "o  
!!    ptions", "condition", "controller", "name_prefix", "trailing_slash_on_root"  
!!    , "locale", "format", "utf8", "exclude", "stateless" in /srv/app/config/rou  
!!    tes/framework.yaml (which is being imported from "/srv/app/src/Kernel.php")  
!!    .                                                                            
!!                                                                                 
!!  
!!  In YamlFileLoader.php line 244:
!!                                                                                 
!!    The routing file "/srv/app/config/routes/framework.yaml" contains unsupport  
!!    ed keys for "when@dev": "_errors". Expected one of: "resource", "type", "pr  
!!    efix", "path", "host", "schemes", "methods", "defaults", "requirements", "o  
!!    ptions", "condition", "controller", "name_prefix", "trailing_slash_on_root"  
!!    , "locale", "format", "utf8", "exclude", "stateless".                        
!!                                                                                 
!!  
!!  cache:clear [--no-warmup] [--no-optional-warmers]
!!  
!!  
```

**Comment by ahbaqdadi** [comment] 2021-06-14 08:58
go to this path : /srv/app/config/routes/framework.yaml and put this code there 
```
_errors:
    resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
    prefix: /_error
```
and delete this label when@dev:

**Comment by dunglas** [comment] 2021-06-14 09:58
Hi, and thanks for reporting!
This issue isn't related with Symfony Docker, it's a problem caused by Flex because of a version mismatch: https://github.com/symfony/recipes/pull/956#pullrequestreview-676802278

Closing this one.

**Closed by dunglas** 2021-06-14 09:58 UTC
